/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as CompaniesNewRouteImport } from './routes/companies.new'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as CustomersCustomerIdIndexRouteImport } from './routes/customers.$customerId.index'
import { Route as CustomersCustomerIdEditRouteImport } from './routes/customers.$customerId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesNewRoute = CompaniesNewRouteImport.update({
  id: '/companies/new',
  path: '/companies/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdIndexRoute =
  CustomersCustomerIdIndexRouteImport.update({
    id: '/customers/$customerId/',
    path: '/customers/$customerId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomersCustomerIdEditRoute = CustomersCustomerIdEditRouteImport.update({
  id: '/customers/$customerId/edit',
  path: '/customers/$customerId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/setup': typeof SetupRoute
  '/companies/new': typeof CompaniesNewRoute
  '/customers/new': typeof CustomersNewRoute
  '/customers/$customerId/edit': typeof CustomersCustomerIdEditRoute
  '/customers/$customerId/': typeof CustomersCustomerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/setup': typeof SetupRoute
  '/companies/new': typeof CompaniesNewRoute
  '/customers/new': typeof CustomersNewRoute
  '/customers/$customerId/edit': typeof CustomersCustomerIdEditRoute
  '/customers/$customerId': typeof CustomersCustomerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/setup': typeof SetupRoute
  '/companies/new': typeof CompaniesNewRoute
  '/customers/new': typeof CustomersNewRoute
  '/customers/$customerId/edit': typeof CustomersCustomerIdEditRoute
  '/customers/$customerId/': typeof CustomersCustomerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/setup'
    | '/companies/new'
    | '/customers/new'
    | '/customers/$customerId/edit'
    | '/customers/$customerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/setup'
    | '/companies/new'
    | '/customers/new'
    | '/customers/$customerId/edit'
    | '/customers/$customerId'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/setup'
    | '/companies/new'
    | '/customers/new'
    | '/customers/$customerId/edit'
    | '/customers/$customerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  SetupRoute: typeof SetupRoute
  CompaniesNewRoute: typeof CompaniesNewRoute
  CustomersNewRoute: typeof CustomersNewRoute
  CustomersCustomerIdEditRoute: typeof CustomersCustomerIdEditRoute
  CustomersCustomerIdIndexRoute: typeof CustomersCustomerIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/new': {
      id: '/companies/new'
      path: '/companies/new'
      fullPath: '/companies/new'
      preLoaderRoute: typeof CompaniesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId/': {
      id: '/customers/$customerId/'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId/'
      preLoaderRoute: typeof CustomersCustomerIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId/edit': {
      id: '/customers/$customerId/edit'
      path: '/customers/$customerId/edit'
      fullPath: '/customers/$customerId/edit'
      preLoaderRoute: typeof CustomersCustomerIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  SetupRoute: SetupRoute,
  CompaniesNewRoute: CompaniesNewRoute,
  CustomersNewRoute: CustomersNewRoute,
  CustomersCustomerIdEditRoute: CustomersCustomerIdEditRoute,
  CustomersCustomerIdIndexRoute: CustomersCustomerIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
